import numpy as np
import pandas as pd

#%% Analysis
file_path = r"data/literary_journal_articles_opencitations_final.xlsx"
df = pd.read_excel(file_path)
articles = df[["article_omid", "venue_name", "citedby_count"]].drop_duplicates().copy()
articles["citedby_count"] = articles["citedby_count"].fillna(0)

mean_agg = {}
median_agg = {}

journal_metrics = []

def gini_coefficient(x):
    """
    Gini coefficient for a 1D array of non-negative values.
    """
    x = np.array(x, dtype=float)

    if len(x) == 0:
        return np.nan

    if np.any(x < 0):
        raise ValueError("Gini coefficient is not defined for negative values.")

    if np.all(x == 0):
        return 0.0

    x_sorted = np.sort(x)
    n = len(x_sorted)
    index = np.arange(1, n + 1)

    gini = (2 * np.sum(index * x_sorted)) / (n * np.sum(x_sorted)) - (n + 1) / n
    return gini


def theil_index(x):
    """
    Theil T index for a 1D array of non-negative values.
    """
    x = np.array(x, dtype=float)

    if len(x) == 0:
        return np.nan

    if np.any(x < 0):
        raise ValueError("Theil index is not defined for negative values.")

    mean_x = np.mean(x)

    if mean_x == 0:
        return 0.0

    ratios = x / mean_x
    ratios = ratios[ratios > 0]  # elementy zerowe nie wnoszą nic do sumy
    return np.mean(ratios * np.log(ratios))


def top_10_citation_share(x):
    """
    Share of all citations generated by the top 10% most cited articles.
    """
    x = np.array(x, dtype=float)

    if len(x) == 0:
        return np.nan

    total_citations = x.sum()

    if total_citations == 0:
        return 0.0

    n_top = max(1, int(np.ceil(len(x) * 0.10)))
    x_sorted_desc = np.sort(x)[::-1]
    top_sum = x_sorted_desc[:n_top].sum()

    return top_sum / total_citations


for venue in sorted(articles["venue_name"].dropna().unique()):
    venue_articles = articles.loc[articles["venue_name"] == venue].copy()
    citations = venue_articles["citedby_count"].astype(float)

    mean_citations = citations.mean()
    median_citations = citations.median()

    mean_agg.update({venue: mean_citations})
    median_agg.update({venue: median_citations})

    citation_distribution = (
        venue_articles.groupby("citedby_count")["article_omid"]
        .nunique()
        .reset_index(name="article_count")
        .sort_values("citedby_count")
    )

    n_articles = len(venue_articles)
    total_citations = citations.sum()

    share_uncited = (citations == 0).mean()
    share_ge_1 = (citations >= 1).mean()
    share_ge_2 = (citations >= 2).mean()
    share_ge_5 = (citations >= 5).mean()
    share_ge_10 = (citations >= 10).mean()

    p95 = citations.quantile(0.95)
    p99 = citations.quantile(0.99)

    mean_median_gap = mean_citations - median_citations

    std_citations = citations.std(ddof=1)
    if mean_citations == 0:
        cv = np.nan if std_citations > 0 else 0.0
    else:
        cv = std_citations / mean_citations

    gini = gini_coefficient(citations)
    theil = theil_index(citations)
    top10_share = top_10_citation_share(citations)

    journal_metrics.append({
        "venue_name": venue,
        "n_articles": n_articles,
        "total_citations": total_citations,
        "mean_citations": mean_citations,
        "median_citations": median_citations,
        "mean_median_gap": mean_median_gap,
        "share_uncited": share_uncited,
        "share_ge_1": share_ge_1,
        "share_ge_2": share_ge_2,
        "share_ge_5": share_ge_5,
        "share_ge_10": share_ge_10,
        "p95_citations": p95,
        "p99_citations": p99,
        "std_citations": std_citations,
        "cv_citations": cv,
        "gini_citations": gini,
        "theil_citations": theil,
        "top_10pct_citation_share": top10_share
    })

journal_metrics_df = pd.DataFrame(journal_metrics).sort_values(
    ["mean_citations", "median_citations"],
    ascending=False
).reset_index(drop=True)

journal_metrics_df.to_excel('data/literary_journal_articles_opencitations_metrics.xlsx', index=False)


#%% Vizualizations

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from adjustText import adjust_text

# === 1. Wczytanie danych ===
file_path = "data/literary_journal_articles_opencitations_metrics.xlsx"
df = pd.read_excel(file_path)

# porządkowanie
df = df.copy()
df = df.sort_values("mean_citations", ascending=False).reset_index(drop=True)

# opcjonalnie: krótsze etykiety pomocnicze
df["label"] = df["venue_name"]

# =========================================================
# WIZUALIZACJA 1
# Bubble plot: mean vs median, size = n_articles, color = gini
# =========================================================

plt.figure(figsize=(12, 9))

scatter = plt.scatter(
    df["median_citations"],
    df["mean_citations"],
    s=df["n_articles"] * 2.5,   # skalowanie bąbli
    c=df["gini_citations"],
    alpha=0.7
)

# etykietujemy tylko najbardziej informacyjne outliery
label_mask = (
    (df["mean_citations"] >= df["mean_citations"].quantile(0.90)) |
    (df["median_citations"] >= df["median_citations"].quantile(0.90)) |
    (df["gini_citations"] >= df["gini_citations"].quantile(0.90))
)

texts = []
for _, row in df[label_mask].iterrows():
    texts.append(
        plt.text(
            row["median_citations"],
            row["mean_citations"],
            row["label"],
            fontsize=9
        )
    )

adjust_text(texts, arrowprops=dict(arrowstyle="-", lw=0.5))

cbar = plt.colorbar(scatter)
cbar.set_label("Gini coefficient")

plt.xlabel("Median citations per article")
plt.ylabel("Mean citations per article")
plt.title("Journal-level citation profiles: mean, median, scale, and inequality")

plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()


# =========================================================
# WIZUALIZACJA 2
# Heatmapa progów cytowań
# =========================================================

heatmap_cols = [
    "share_uncited",
    "share_ge_1",
    "share_ge_2",
    "share_ge_5",
    "share_ge_10"
]

heatmap_df = (
    df[["venue_name"] + heatmap_cols]
    .sort_values(["share_ge_10", "share_ge_5", "share_ge_2", "share_ge_1"], ascending=False)
    .set_index("venue_name")
)

plt.figure(figsize=(10, 18))
plt.imshow(heatmap_df.values, aspect="auto")

plt.yticks(range(len(heatmap_df.index)), heatmap_df.index, fontsize=8)
plt.xticks(range(len(heatmap_df.columns)), heatmap_df.columns, rotation=45, ha="right")

cbar = plt.colorbar()
cbar.set_label("Share of articles")

plt.title("Citation threshold profile of journals")
plt.tight_layout()
plt.show()


# =========================================================
# WIZUALIZACJA 3
# Reżimy cytacyjne: share_uncited vs top_10pct_citation_share
# =========================================================

plt.figure(figsize=(12, 9))

scatter2 = plt.scatter(
    df["share_uncited"],
    df["top_10pct_citation_share"],
    s=df["total_citations"] * 0.8 + 20,
    c=df["p95_citations"],
    alpha=0.7
)

# linie referencyjne: mediany
x_med = df["share_uncited"].median()
y_med = df["top_10pct_citation_share"].median()

plt.axvline(x_med, linestyle="--", linewidth=1)
plt.axhline(y_med, linestyle="--", linewidth=1)

# etykiety dla najbardziej interesujących tytułów
label_mask2 = (
    (df["share_uncited"] >= df["share_uncited"].quantile(0.90)) |
    (df["top_10pct_citation_share"] >= df["top_10pct_citation_share"].quantile(0.90)) |
    (df["mean_citations"] >= df["mean_citations"].quantile(0.90))
)

texts2 = []
for _, row in df[label_mask2].iterrows():
    texts2.append(
        plt.text(
            row["share_uncited"],
            row["top_10pct_citation_share"],
            row["label"],
            fontsize=9
        )
    )

adjust_text(texts2, arrowprops=dict(arrowstyle="-", lw=0.5))

cbar2 = plt.colorbar(scatter2)
cbar2.set_label("95th percentile of citations")

plt.xlabel("Share of uncited articles")
plt.ylabel("Share of citations generated by top 10% of articles")
plt.title("Citation regimes of journals: uncitedness vs concentration")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()


#%%





































